export default {
  login: "jayden-leuciuc",
  id: 68298467,
  node_id: "MDQ6VXNlcjY4Mjk4NDY3",
  avatar_url: "https://avatars0.githubusercontent.com/u/68298467?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/jayden-leuciuc",
  html_url: "https://github.com/jayden-leuciuc",
  followers_url: "https://api.github.com/users/jayden-leuciuc/followers",
  following_url: "https://api.github.com/users/jayden-leuciuc/following{/other_user}",
  gists_url: "https://api.github.com/users/jayden-leuciuc/gists{/gist_id}",
  starred_url: "https://api.github.com/users/jayden-leuciuc/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/jayden-leuciuc/subscriptions",
  organizations_url: "https://api.github.com/users/jayden-leuciuc/orgs",
  repos_url: "https://api.github.com/users/jayden-leuciuc/repos",
  events_url: "https://api.github.com/users/jayden-leuciuc/events{/privacy}",
  received_events_url: "https://api.github.com/users/jayden-leuciuc/received_events",
  type: "User",
  site_admin: false,
  name: "Jayden Leuciuc",
  company: null,
  blog: "https://linktr.ee/jayden.leuciuc",
  location: "United States",
  email: null,
  hireable: null,
  bio: "Self-taught web developer, based in Tennessee.",
  twitter_username: "leuciucjayden",
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2020-07-14T18:46:23Z",
  updated_at: "2020-12-16T02:12:34Z"
}